language: python
# python:
#     - "3.6"
#     - "3.7"

matrix:
    fast_finish: true
    allow_failures:
        - python: "3.7"  # Travis CI not supporting 3.7 yet
matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
     - python: 3.7
      env: TOXENV=py37     
      
      fast_finish: true


install: pip install tox

script: tox



# command to install dependencies
install:
    - pip install -r requirements.txt


# command to run tests
script:
    - pytest
