language: python
python:
    - "3.6"
    - "3.7"

matrix:
    fast_finish: true
    allow_failures:
        - python: "3.7"  # Travis CI not supporting 3.7 yet

before_install:
    - "export PYTHONPATH=$PYTHONPATH:$(pwd)"
    - "pip install -U pip"
#    - "python setup.py install" or "develop"

# command to install dependencies
install:
    - pip install -r requirements.txt
    - pip install -e .

# command to run tests
script:
    - pytest
