# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:

      - checkout

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements_dev.txt
            pip install -r requirements.txt

      - run:
          name: run tests
          command: |
            . venv/bin/activate

            pytest -v --cov=dionysus
            coverage xml
            python-codacy-coverage -r coverage.xml